/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"


#include "Driver_Adc.h"
#include "Driver_Stm.h"
#include "GTM_TOM_PWM.h"
#include "FNDSPI.h"
#include "DHT11.h"
#include "Bsp.h"
#include "dht11_driver.h"

#define DHT11_UPDATE_TIME                   500000000
#define SCLK IfxPort_P00_0
#define RCLK IfxPort_P00_1
#define DIO IfxPort_P00_2
IfxCpu_syncEvent g_cpuSyncEvent = 0;

void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

void initGPIO(void);
void initERU(void);
void send(unsigned char X);
void send_port(unsigned char X, unsigned char port);

typedef struct
{
    uint32_t u32nuCnt1ms;
    uint32_t u32nuCnt10ms;
    uint32_t u32nuCnt100ms;
    uint32_t u32nuCnt1000ms;

}TestCnt;
TestCnt stTestCnt;

uint8_t _LED_0F[10] = {0xC0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90};
int n1, n2, n3, n4;
uint8 temp;
uint32_t adcResult = 0;
uint8_t hum = 0;
volatile int cnt = 0;
int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
//    initFND();
    initGPIO();
    Driver_Stm_Init();
    DHT11_init_comm();

    while(1) {
        AppScheduling();

//        adcResult = (uint32_t)g_dht11_one_eye_data.humidity;
        adcResult = hum;

        n1 = (uint32_t) adcResult%10;
        n2 = (uint32_t) (adcResult%100)/10;
        n3 = (uint32_t) (adcResult%1000)/100;
        n4 = (uint32_t) (adcResult%10000)/1000;

        send_port(_LED_0F[n1],0x1);
        send_port(_LED_0F[n2],0x2);
        send_port(_LED_0F[n3]&0x7f,0x4);
        send_port(_LED_0F[n4],0x8);

//        fadeLED(adcResult);
//        setFNDNumber(temp);
    }
    return (1);
}

void initGPIO(){
    IfxPort_setPinModeOutput(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex,IfxPort_OutputMode_pushPull,IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex,IfxPort_OutputMode_pushPull,IfxPort_OutputIdx_general);
    IfxPort_setPinLow(IfxPort_P10_1.port, IfxPort_P10_1.pinIndex);
    IfxPort_setPinHigh(IfxPort_P10_2.port, IfxPort_P10_2.pinIndex);
}

void AppScheduling(void){
    if(stSchedulingInfo.u8nuScheduling1msFlag){
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();
        if(stSchedulingInfo.u8nuScheduling10msFlag){
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();

            if(stSchedulingInfo.u8nuScheduling100msFlag){
                stSchedulingInfo.u8nuScheduling100msFlag = 0u;
                AppTask100ms();

                if(stSchedulingInfo.u8nuScheduling1000msFlag){
                    stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
                    AppTask1000ms();
                }
            }
        }
    }
}

void send(unsigned char X)
{

  for (int i = 8; i >= 1; i--)
  {
    if (X & 0x80)
    {
      //digitalWrite(_DIO, HIGH);
      IfxPort_setPinHigh(DIO.port, DIO.pinIndex);
    }
    else
    {
//      digitalWrite(_DIO, LOW);
      IfxPort_setPinLow(DIO.port, DIO.pinIndex);
    }
    X <<= 1;
//    digitalWrite(_SCLK, LOW);
//    digitalWrite(_SCLK, HIGH);
    IfxPort_setPinLow(SCLK.port, SCLK.pinIndex);
    IfxPort_setPinHigh(SCLK.port, SCLK.pinIndex);

  }
}

void send_port(unsigned char X, unsigned char port)
{
  send(X);
  send(port);
//  digitalWrite(_RCLK, LOW);
//  digitalWrite(_RCLK, HIGH);
  IfxPort_setPinLow(RCLK.port, RCLK.pinIndex);
  IfxPort_setPinHigh(RCLK.port, RCLK.pinIndex);
}

void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
//    DHT11_read_sensor();
//    if(g_dht11_one_eye_data.data_valid){
//        temp = g_dht11_one_eye_data.humidity;
//    }
}

void AppTask1000ms(void)
{

    stTestCnt.u32nuCnt1000ms++;
    // DHT11은 2초마다 갱신해야
    if (stTestCnt.u32nuCnt1000ms&0x1) { // == stTestCnt.u32nuCnt1000ms % 2
//        DHT11_read_sensor();
        DHT11_Start();
        if (Check_Response()) P10_OUT.U = 0x4;
        else P10_OUT.U = 0x0;
        hum = DHT11_Read();
        DHT11_Read();
        DHT11_Read();
        DHT11_Read();
        DHT11_Read();

    }

}
