/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "Driver_Stm.h"

//GPIO related
#define PCn_2_IDX 19
#define P2_IDX 2
#define PCn_1_IDX 11
#define PCn_0_IDX 3
#define P1_IDX 1

//SPI port define
#define SCLK IfxPort_P00_0
#define RCLK IfxPort_P00_1
#define DIO  IfxPort_P00_2

// ERU related
#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11

//typedef struct
//{
//    uint32_t u32nuCnt1ms;
//    uint32_t u32nuCnt10ms;
//    uint32_t u32nuCnt100ms;
//    uint32_t u32nuCnt1000ms;
//
//}TestCnt;

uint32_t u32nuCnt10ms = 0;

// Task scheduling related
void AppScheduling(void);
//void AppTask1ms(void);
void AppTask10ms(void);
//void AppTask100ms(void);
//void AppTask1000ms(void);

void send(uint8_t X);
void send_port(uint8_t X, uint8_t port);

/***********************************************************************/
/*Variable*/
/***********************************************************************/
//TestCnt stTestCnt;
uint8_t _LED_0F[10] = {0xC0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90};

IfxCpu_syncEvent g_cpuSyncEvent = 0;

//void initGPIO(void);


int core0_main(void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

//    initGPIO();
    P10_IOCR0.U = 0x00808000;
    P00_IOCR0.U = 0x00808080;
    Driver_Stm_Init();

//    int n4;
    while(1)
    {
        AppScheduling();
//        n4 = ((int)stTestCnt.u32nuCnt1000ms/10) % 10;
//        send_port(_LED_0F[stTestCnt.u32nuCnt10ms % 10],0x1);
//        send_port(_LED_0F[stTestCnt.u32nuCnt100ms % 10],0x2);
//        send_port(_LED_0F[stTestCnt.u32nuCnt1000ms % 10]&0x7f,0x4);
//        send_port(_LED_0F[n4],0x8);

//        n4 = u32nuCnt10ms;
        send_port(_LED_0F[u32nuCnt10ms % 10], 0x1);
        send_port(_LED_0F[(u32nuCnt10ms / 10) % 10], 0x2);
        send_port(_LED_0F[(u32nuCnt10ms / 100) % 10] & 0x7f, 0x4);
        send_port(_LED_0F[(u32nuCnt10ms / 1000) % 10], 0x8);
    }
    return (1);
}

//void initGPIO(void){
////    P10_IOCR0.U &= ~(0x1F << PCn_2_IDX);
////    P10_IOCR0.U |= 0x10 << PCn_2_IDX;
////    P10_IOCR0.U &= ~(0x1F << PCn_1_IDX);
////    P10_IOCR0.U |= 0x10 << PCn_1_IDX;
////    P00_IOCR0.U &= ~(0x1F << PCn_0_IDX);
////    P00_IOCR0.U |= 0x10 << PCn_0_IDX;
////    P00_IOCR0.U &= ~(0x1F << PCn_1_IDX);
////    P00_IOCR0.U |= 0x10 << PCn_1_IDX;
////    P00_IOCR0.U &= ~(0x1F << PCn_2_IDX);
////    P00_IOCR0.U |= 0x10 << PCn_2_IDX;
//}

void send(uint8_t X){
    for (int i = 8; i > 0; i--)
    {
//      if (X & 0x80)
//      {
////        IfxPort_setPinHigh(DIO.port, DIO.pinIndex);
//        P00_OMR.U = 0x4;
//      }
//      else
//      {
////        IfxPort_setPinLow(DIO.port, DIO.pinIndex);
//        P00_OMR.U = 0x40000;
//      }
////      X <<= 1;
//

      P00_OMR.U = (X & 0x80) ? 0x4 : 0x40000;

      X = (X + X);
      P00_OMR.U |= 0x10000;
      P00_OMR.U |= 0x1;
//      IfxPort_setPinLow(SCLK.port, SCLK.pinIndex);
//      IfxPort_setPinHigh(SCLK.port, SCLK.pinIndex);
    }
}
void send_port(uint8_t X, uint8_t port){
    send(X);
    send(port);

    P00_OMR.U |= 0x20000;
    P00_OMR.U |= 0x2;
//    IfxPort_setPinLow(RCLK.port, RCLK.pinIndex);
//    IfxPort_setPinHigh(RCLK.port, RCLK.pinIndex);
}

//void AppTask1ms(void)
//{
//    stTestCnt.u32nuCnt1ms++;
//}

void AppTask10ms(void)
{
    u32nuCnt10ms++;

    // 100ms
    if (u32nuCnt10ms % 10 == 0) {
        P10_OMR.U = 0x20002;
    }

    // 1000ms
    if (u32nuCnt10ms % 100 == 0) {
        P10_OMR.U = 0x40004;
    }
}


//void AppTask100ms(void)
//{
//    P10_OMR.U = 0x20002;
//    stTestCnt.u32nuCnt100ms++;
//}

//void AppTask1000ms(void)
//{
//    P10_OMR.U = 0x40004;
//    stTestCnt.u32nuCnt1000ms++;
//}

void AppScheduling(void)
{
//    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
//    {
//        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
//        AppTask1ms();

//        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
//        {
//            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
//            AppTask10ms();
//        }

//        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
//        {
//            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
//            AppTask100ms();
//        }
//        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
//        {
//            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
//            AppTask1000ms();
//        }
//    }
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }
    }
}
